apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-zaak.fullname" . }}
  labels:
    {{- include "open-zaak.labels" . | nindent 4 }}
data:
  ALLOWED_HOSTS: {{ .Values.settings.allowedHosts | toString | quote }}
  DB_HOST: {{ .Values.settings.database.host | toString | quote }}
  DB_PORT: {{ .Values.settings.database.port | toString | quote }}
  DB_USER: {{ .Values.settings.database.username | toString | quote }}
  DB_NAME: {{ .Values.settings.database.name | toString | quote }}
  EMAIL_HOST: {{ .Values.settings.email.host | toString | quote }}
  {{- if .Values.settings.email.username }}
  EMAIL_USER: {{ .Values.settings.email.username | toString | quote }}
  {{- end }}
  {{- if .Values.settings.email.useTLS }}
  EMAIL_USE_TLS: 'True'
  {{- end }}
