apiVersion: v2
name: open-zaak
description: A Helm chart for Kubernetes

type: application
version: 0.2.3
appVersion: 1.16.0

dependencies:
  - name: postgresql
    version: ~10.2.0
    repository: https://charts.bitnami.com/bitnami
    tags:
      - postgresql
  - name: redis
    version: ~12.2.2
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
